version: "3.7"
services:
  server:
    build: server
    ports:
      - "5000:5000"
  client:
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - NODE_ENV=prod
    build: client
    ports:
      - "80:80"
    depends_on:
      - server
